server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/yikun?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml